"""add_transaction_fields

Revision ID: a1b2c3d4e5f6
Revises: fb0947bcd80a
Create Date: 2025-12-10 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'fb0947bcd80a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('reference_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reference_number')
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
