"""add_is_verified

Revision ID: fb0947bcd80a
Revises: f8f4e4bf9de2
Create Date: 2025-12-10 10:49:09.685615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0947bcd80a'
down_revision = 'f8f4e4bf9de2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
